export const SHOW_PRODUCT_DETAILS = 'SHOW_PRODUCT_DETAILS'
export const DISMISS_PRODUCT_DETAILS = 'DISMISS_PRODUCT_DETAILS'
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART'
export const CLEAR_CART = 'CLEAR_CART'
